const trimTrailingSlash = (value: string) => value.replace(/\/+$/, '');

const getApiBaseUrl = () => {
  const configuredBaseUrl = String(import.meta.env.VITE_API_BASE_URL || '').trim();
  const configuredOrigin = String(import.meta.env.VITE_API_ORIGIN || '').trim();
  if (configuredBaseUrl) {
    if (
      import.meta.env.PROD &&
      configuredOrigin &&
      configuredBaseUrl.startsWith('/') &&
      !configuredBaseUrl.startsWith('//')
    ) {
      return `${trimTrailingSlash(configuredOrigin)}${configuredBaseUrl}`;
    }
    return trimTrailingSlash(configuredBaseUrl);
  }

  return '/api';
};

const getOriginBaseUrl = (apiBaseUrl: string) => {
  const configuredOrigin = String(import.meta.env.VITE_API_ORIGIN || '').trim();
  if (configuredOrigin) {
    return trimTrailingSlash(configuredOrigin);
  }

  if (/^https?:\/\//i.test(apiBaseUrl)) {
    return trimTrailingSlash(apiBaseUrl.replace(/\/api$/i, ''));
  }

  return '';
};

const API_BASE_URL = getApiBaseUrl();
const API_ORIGIN = getOriginBaseUrl(API_BASE_URL);

// API Configuration
export const API_CONFIG = {
  BASE_URL: API_BASE_URL,
  BASE_URL_WITHOUT_API: API_ORIGIN,
  ENDPOINTS: {
    STATISTICS_DATA: '/statistics-data',
    AUTH: '/auth',
    MEDICAL: '/medical',
    SAVE_EXAMINATION: '/save-examination',
    SAVE_PROCEDURES: '/save-procedures',
    LABORATORY_DATA: '/laboratory-data',
    LABORATORY_DATA_ACCESS: '/laboratory-data/access',
    RADIOLOGY_DATA: '/radiology-data',
    RADIOLOGY_DATA_ACCESS: '/radiology-data/access',
    PRESCRIPTION_DATA: '/prescription-data',
    DOCTOR_NOTIFICATIONS: '/doctor-notifications',
    DEPO_FARMASI: '/depo-farmasi',
    DOCTOR_NOTIFICATION_RESULT: '/doctor-notifications/result',
    ALLERGY_DATA: '/allergy-data',
    ASSESMEN_REHAB_MEDIK: '/assesmen-rehab-medik',
    ASSESMEN_REHAB_MEDIK_ACCESS: '/assesmen-rehab-medik/access',
    BALANCE_CAIRAN: '/balance-cairan',
    VENTILATOR: '/ventilator',
    ECHOCARDIOGRAPHY: '/echocardiography',
    ECHOCARDIOGRAPHY_ACCESS: '/echocardiography/access',
    EKSTRAPIRAMIDAL: '/ekstrapiramidal',
    PATIENT_CONTACT: '/patient-contact',
    PATIENT_CONTACT_MESSAGE: '/patient-contact/message',
    PROCEDURE_OPTIONS: '/procedure-options',
    DELETE_PROCEDURE: '/delete-procedure',
    UPDATE_EXAMINATION: '/update-examination',
    WHATSAPP_OTP: '/whatsapp-otp',
    BOOKING_REGISTRASI: '/booking-registrasi',
    BOOKING_OPERASI_DATA: '/booking-operasi-data',
    RAWAT_JALAN_PATIENTS: '/rawat-jalan-patients',
    RAWAT_INAP_DATA: '/rawat-inap-data',
    RESUME_PASIEN_DATA: '/resume-pasien-data',
    RESUME_PASIEN_VERIFICATION: '/resume-pasien-data',
    IGD_DATA: '/igd-data',
    TRIAGE_IGD: '/triase-igd',
    GET_MEDICAL_RECORD: '/get-medical-record',
    GET_MEDICAL_RECORD_VISIT_DETAILS: '/get-medical-record-visit-details',
    GET_MEDICAL_RECORD_EXAMINATIONS: '/get-medical-record-examinations',
    SEARCH_MEDICAL_RECORD_PATIENTS: '/search-medical-record-patients',
    DELETE_EXAMINATION: '/delete-examination',
    DASHBOARD_DATA: '/dashboard-data',
    ICD_DATA: '/icd-data',
    ICD_MANAGEMENT: '/icd-management',
    INACBG_SIMULATION: '/inacbg-simulation',
    ATTENDANCE_DATA: '/attendance-data',
    HEMODIALISA_DATA: '/hemodialisa-data',
    MEDICAL_SCRIBE: '/medical-scribe',
    VOICE_TO_SOAP: '/voice-to-soap',
    DOCTOR_AI_ASSISTANT: '/doctor-ai-assistant',
    DOCTOR_AI_ASSISTANT_LOGS: '/doctor-ai-assistant/logs',
    CLINICAL_PATHWAY: '/clinical-pathway',
    CLINICAL_PATHWAY_ACCESS: '/clinical-pathway/access',
    PATIENT_NOTES: '/patient-notes',
    PATIENT_NOTES_HISTORY: '/patient-notes-history',
    OPERATION_REPORTS: '/operation-reports',
    OPERATION_REPORT_DIGITAL_FILES: '/operation-reports',
    OPERATION_REPORT_DIGITAL_FILES_UPLOAD: '/operation-reports/files/upload',
    INTERNAL_REFERRALS: '/internal-referrals',
    INTERNAL_REFERRAL_DOCTORS: '/internal-referrals/doctors',
    DIGITAL_FILES: '/digital-files',
    DIGITAL_FILES_OPTIONS: '/digital-files/options',
    DIGITAL_FILES_UPLOAD: '/digital-files/upload',
    AUDIT_HISTORY: '/audit-history',
    AUDIT_HISTORY_ACCESS: '/audit-history/access'
  }
};

// Helper function to build full API URLs
export const buildApiUrl = (endpoint: string) => {
  return `${API_CONFIG.BASE_URL}${endpoint}`;
};

// Specific API URLs
export const API_URLS = {
  STATISTICS_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.STATISTICS_DATA),
  AUTH: buildApiUrl(API_CONFIG.ENDPOINTS.AUTH),
  MEDICAL: buildApiUrl(API_CONFIG.ENDPOINTS.MEDICAL),
  SAVE_EXAMINATION: buildApiUrl(API_CONFIG.ENDPOINTS.SAVE_EXAMINATION),
  SAVE_PROCEDURES: buildApiUrl(API_CONFIG.ENDPOINTS.SAVE_PROCEDURES),
  LABORATORY_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.LABORATORY_DATA),
  LABORATORY_DATA_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.LABORATORY_DATA_ACCESS),
  RADIOLOGY_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.RADIOLOGY_DATA),
  RADIOLOGY_DATA_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.RADIOLOGY_DATA_ACCESS),
  PRESCRIPTION_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.PRESCRIPTION_DATA),
  DOCTOR_NOTIFICATIONS: buildApiUrl(API_CONFIG.ENDPOINTS.DOCTOR_NOTIFICATIONS),
  DEPO_FARMASI: buildApiUrl(API_CONFIG.ENDPOINTS.DEPO_FARMASI),
  DOCTOR_NOTIFICATION_RESULT: buildApiUrl(API_CONFIG.ENDPOINTS.DOCTOR_NOTIFICATION_RESULT),
  ALLERGY_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.ALLERGY_DATA),
  ASSESMEN_REHAB_MEDIK: buildApiUrl(API_CONFIG.ENDPOINTS.ASSESMEN_REHAB_MEDIK),
  ASSESMEN_REHAB_MEDIK_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.ASSESMEN_REHAB_MEDIK_ACCESS),
  BALANCE_CAIRAN: buildApiUrl(API_CONFIG.ENDPOINTS.BALANCE_CAIRAN),
  VENTILATOR: buildApiUrl(API_CONFIG.ENDPOINTS.VENTILATOR),
  ECHOCARDIOGRAPHY: buildApiUrl(API_CONFIG.ENDPOINTS.ECHOCARDIOGRAPHY),
  ECHOCARDIOGRAPHY_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.ECHOCARDIOGRAPHY_ACCESS),
  EKSTRAPIRAMIDAL: buildApiUrl(API_CONFIG.ENDPOINTS.EKSTRAPIRAMIDAL),
  PATIENT_CONTACT: buildApiUrl(API_CONFIG.ENDPOINTS.PATIENT_CONTACT),
  PATIENT_CONTACT_MESSAGE: buildApiUrl(API_CONFIG.ENDPOINTS.PATIENT_CONTACT_MESSAGE),
  PROCEDURE_OPTIONS: buildApiUrl(API_CONFIG.ENDPOINTS.PROCEDURE_OPTIONS),
  DELETE_PROCEDURE: buildApiUrl(API_CONFIG.ENDPOINTS.DELETE_PROCEDURE),
  UPDATE_EXAMINATION: buildApiUrl(API_CONFIG.ENDPOINTS.UPDATE_EXAMINATION),
  WHATSAPP_OTP: buildApiUrl(API_CONFIG.ENDPOINTS.WHATSAPP_OTP),
  BOOKING_REGISTRASI: buildApiUrl(API_CONFIG.ENDPOINTS.BOOKING_REGISTRASI),
  BOOKING_OPERASI_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.BOOKING_OPERASI_DATA),
  RAWAT_JALAN_PATIENTS: buildApiUrl(API_CONFIG.ENDPOINTS.RAWAT_JALAN_PATIENTS),
  RAWAT_INAP_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.RAWAT_INAP_DATA),
  RESUME_PASIEN_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.RESUME_PASIEN_DATA),
  RESUME_PASIEN_VERIFICATION: buildApiUrl(API_CONFIG.ENDPOINTS.RESUME_PASIEN_VERIFICATION),
  IGD_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.IGD_DATA),
  TRIAGE_IGD: buildApiUrl(API_CONFIG.ENDPOINTS.TRIAGE_IGD),
  GET_MEDICAL_RECORD: buildApiUrl(API_CONFIG.ENDPOINTS.GET_MEDICAL_RECORD),
  GET_MEDICAL_RECORD_VISIT_DETAILS: buildApiUrl(API_CONFIG.ENDPOINTS.GET_MEDICAL_RECORD_VISIT_DETAILS),
  GET_MEDICAL_RECORD_EXAMINATIONS: buildApiUrl(API_CONFIG.ENDPOINTS.GET_MEDICAL_RECORD_EXAMINATIONS),
  SEARCH_MEDICAL_RECORD_PATIENTS: buildApiUrl(API_CONFIG.ENDPOINTS.SEARCH_MEDICAL_RECORD_PATIENTS),
  DELETE_EXAMINATION: buildApiUrl(API_CONFIG.ENDPOINTS.DELETE_EXAMINATION),
  DASHBOARD_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.DASHBOARD_DATA),
  ICD_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.ICD_DATA),
  ICD_MANAGEMENT: buildApiUrl(API_CONFIG.ENDPOINTS.ICD_MANAGEMENT),
  INACBG_SIMULATION: buildApiUrl(API_CONFIG.ENDPOINTS.INACBG_SIMULATION),
  ATTENDANCE_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.ATTENDANCE_DATA),
  HEMODIALISA_DATA: buildApiUrl(API_CONFIG.ENDPOINTS.HEMODIALISA_DATA),
  MEDICAL_SCRIBE: buildApiUrl(API_CONFIG.ENDPOINTS.MEDICAL_SCRIBE),
  VOICE_TO_SOAP: buildApiUrl(API_CONFIG.ENDPOINTS.VOICE_TO_SOAP),
  DOCTOR_AI_ASSISTANT: buildApiUrl(API_CONFIG.ENDPOINTS.DOCTOR_AI_ASSISTANT),
  DOCTOR_AI_ASSISTANT_LOGS: buildApiUrl(API_CONFIG.ENDPOINTS.DOCTOR_AI_ASSISTANT_LOGS),
  CLINICAL_PATHWAY: buildApiUrl(API_CONFIG.ENDPOINTS.CLINICAL_PATHWAY),
  CLINICAL_PATHWAY_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.CLINICAL_PATHWAY_ACCESS),
  PATIENT_NOTES: buildApiUrl(API_CONFIG.ENDPOINTS.PATIENT_NOTES),
  PATIENT_NOTES_HISTORY: buildApiUrl(API_CONFIG.ENDPOINTS.PATIENT_NOTES_HISTORY),
  OPERATION_REPORTS: buildApiUrl(API_CONFIG.ENDPOINTS.OPERATION_REPORTS),
  OPERATION_REPORT_DIGITAL_FILES: buildApiUrl(API_CONFIG.ENDPOINTS.OPERATION_REPORT_DIGITAL_FILES),
  OPERATION_REPORT_DIGITAL_FILES_UPLOAD: buildApiUrl(API_CONFIG.ENDPOINTS.OPERATION_REPORT_DIGITAL_FILES_UPLOAD),
  INTERNAL_REFERRALS: buildApiUrl(API_CONFIG.ENDPOINTS.INTERNAL_REFERRALS),
  INTERNAL_REFERRAL_DOCTORS: buildApiUrl(API_CONFIG.ENDPOINTS.INTERNAL_REFERRAL_DOCTORS),
  DIGITAL_FILES: buildApiUrl(API_CONFIG.ENDPOINTS.DIGITAL_FILES),
  DIGITAL_FILES_OPTIONS: buildApiUrl(API_CONFIG.ENDPOINTS.DIGITAL_FILES_OPTIONS),
  DIGITAL_FILES_UPLOAD: buildApiUrl(API_CONFIG.ENDPOINTS.DIGITAL_FILES_UPLOAD),
  AUDIT_HISTORY: buildApiUrl(API_CONFIG.ENDPOINTS.AUDIT_HISTORY),
  AUDIT_HISTORY_ACCESS: buildApiUrl(API_CONFIG.ENDPOINTS.AUDIT_HISTORY_ACCESS)
};
